fos_rest:
    param_fetcher_listener: false
    body_listener: false
    format_listener:
        enabled: true
        rules:            
            - { path: '.json$', priorities: ['json'], fallback_format: 'html' }
            - { path: '^/', priorities: ['html'], fallback_format: 'html' }
    versioning: true
    view:
        view_response_listener: 'force'